Display diagnostic in Java file after loading of MP Java project
eclipse/lsp4mp pull request #300
Opened 2022-10-19 09:12 UTC by angelozerr

Display diagnostic in Java file after loading of MP Java project

Fixes #301

Signed-off-by: azerr <azerr@redhat.com>

2022-10-19 10:05 UTC, jeffmaury commented
Fixes #301

2022-10-19 10:09 UTC, angelozerr commented
As @rgrunber noticed, there is the same problem with inlay hint for properties file. This PR should fix too the problem.

2022-10-19 13:00 UTC, angelozerr commented
I would like to investigate if I could write easily some tests with thoses fixes.

2022-10-24 15:59 UTC, datho7561 requested changes
This change is working well. Thanks, Angelo! I noticed a small mistake in some of the comments

2022-10-24 15:59 UTC, datho7561 commented on microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/ls/java/JavaTextDocuments.java
> +		 * without waiting for the load of project information. project.
Remove " project." from the comment

2022-10-24 15:59 UTC, datho7561 commented on microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/ls/java/JavaTextDocuments.java
> +		 *         project without waiting for the load of project information. project.
Remove " project." from the comment

2022-10-26 14:42 UTC, angelozerr commented on microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/ls/java/JavaTextDocuments.java
> +		 *         project without waiting for the load of project information. project.
fixed

2022-10-26 14:42 UTC, angelozerr commented on microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/ls/java/JavaTextDocuments.java
> +		 * without waiting for the load of project information. project.
fixed

2022-10-26 14:42 UTC, angelozerr commented
Ok now we have tests with diagnostics and inlay hint when project is loading.

2022-10-26 15:11 UTC, datho7561 approved these changes
Looks good to me. Thanks, Angelo!

2022-10-26 15:12 UTC, merged