Manage static properties using a staticProvider extension point
eclipse/lsp4mp pull request #306
Opened 2022-11-01 19:31 UTC by JessicaJHee

Fixes #44 

Signed-off-by: Jessica He <jhe@redhat.com>

2022-11-02 20:02 UTC, datho7561 requested changes

2022-11-02 20:02 UTC, datho7561 commented on microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/core/StaticProviderRegistry.java
> +        return "staticProviders";
I think it makes more sense to call this extension point `staticPropertyProviders`, just to be extra clear.

2022-11-03 17:39 UTC, rgrunber commented on microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/core/StaticPropertyProvider.java
> +    String type;
Can this be made private ? Looks like you only is it for `isAdaptedFor(..)`. If you ever needed to use it outside this class, just create a getter and keep it private.

2022-11-03 17:40 UTC, rgrunber commented on microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/core/StaticPropertyProviderRegistry.java
> +        super();
I don't think you need `super()` here. It's just implementing an interface. There's no parent class that with a no-arg constructor to be called, unless I'm missing something.

2022-11-07 15:50 UTC, datho7561 requested changes
A few comments on some code formatting, but it appears to be working well! Thanks, Jessica!

2022-11-07 15:50 UTC, datho7561 commented on microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/core/StaticPropertyProvider.java
> +/*******************************************************************************
Replace spaces with tabs (sorry this is an IDE setting I accidentally modified during one of my previous PRs)

2022-11-07 15:50 UTC, datho7561 commented on microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/jdt/internal/core/StaticPropertyProviderRegistry.java
> +public class StaticPropertyProviderRegistry implements IRegistryChangeListener {
Replace spaces with tabs

2022-11-07 17:11 UTC, datho7561 approved these changes
Looks good, thanks Jessica!

2022-11-07 17:13 UTC, merged