Support jakarta namespace with Inject annotation
eclipse/lsp4mp pull request #350
Opened 2023-01-31 19:11 UTC by JessicaJHee

![Peek 2023-01-31 14-03](https://user-images.githubusercontent.com/73968480/215859364-fb2c755b-bd6c-44bb-87fa-94b7a5c4c181.gif)

Fixes #344 

Signed-off-by: Jessica He <jhe@redhat.com>

2023-01-31 19:13 UTC, JessicaJHee commented
With a project that uses the `javax` namespace: 
![Peek 2023-01-31 14-05](https://user-images.githubusercontent.com/73968480/215859656-e9fa7740-79b6-4bbd-ac69-f718fa331dd5.gif)

2023-01-31 19:57 UTC, datho7561 requested changes
I think it would be nice to avoid having another test project in the folder, especially given I added one that's fairly similar, but other than that, this PR works very well!

I think it makes sense to split up the PRs for each of the different features that we need to migrate to the jakarta namespace. That way, the PRs are smaller and easier to review, and if you need to shift focus onto other issues, someone else can work on them.

2023-01-31 19:57 UTC, datho7561 commented on microprofile.jdt/org.eclipse.lsp4mp.jdt.test/projects/maven/rest-client-ee9/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
I have included a project "open-liberty" that should be almost the same as this project (i.e. it uses the `jakarta` namespace). See if you can get away with just using that one (just to save space).

2023-01-31 19:57 UTC, angelozerr commented
Your demo are great but I wonder if the import of Inject doesnt exist if the code action insert the proper import.

If no you could do that in a separate pr.

2023-01-31 21:06 UTC, JessicaJHee commented
> Your demo are great but I wonder if the import of Inject doesnt exist if the code action insert the proper import.

I believe it should import with the proper namespace based on the project set up. In my demo with a project using the javax namespace, it imports `javax.inject.Inject`.

With a project using `jakarta`, it should work like this: 
![Peek 2023-01-31 16-02](https://user-images.githubusercontent.com/73968480/215882657-fd47abfb-e4b5-4531-949f-81ebbf81cf2c.gif)

2023-01-31 21:18 UTC, datho7561 commented on microprofile.jdt/org.eclipse.lsp4mp.jdt.tp/org.eclipse.lsp4mp.jdt.target
> +		<location type="Target" uri="https://raw.githubusercontent.com/eclipse/eclipse.jdt.ls/master/org.eclipse.jdt.ls.target/org.eclipse.jdt.ls.tp.target"/>
Make sure to recomment this line

2023-02-01 13:52 UTC, datho7561 approved these changes
Looks good and works like a charm. Thanks, Jessica!

2023-02-01 13:58 UTC, datho7561 commented
I'm going to merge this PR but leave #344 open until we handle the rest of the cases where `javax` is used.

2023-02-01 13:58 UTC, merged