feat: Resolve system properties/environment variables while browsing the application.properties values
eclipse/lsp4mp pull request #456
Opened 2024-08-14 12:14 UTC by angelozerr

feat: Resolve system properties/environment variables while browsing the application.properties values

Fixes #448

2024-08-14 12:17 UTC, fbricon commented on microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/extensions/sysenv/SysEnvItemMetadataProvider.java
> +		return upKey.endsWith("_KEY") || upKey.endsWith("_SECRET") ? "*********" : value;
can you add _PASSWORD too?

2024-08-14 12:31 UTC, gastaldi commented on microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/extensions/sysenv/SysEnvItemMetadataProvider.java
> +		return upKey.endsWith("_KEY") || upKey.endsWith("_SECRET") ? "*********" : value;
Maybe `_TOKEN` as well?

2024-08-14 13:09 UTC, angelozerr commented on microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/extensions/sysenv/SysEnvItemMetadataProvider.java
> +		return upKey.endsWith("_KEY") || upKey.endsWith("_SECRET") ? "*********" : value;
Added

2024-08-14 15:36 UTC, datho7561 commented
Hovering on the system property/environment variable names causes an error popup

2024-08-14 15:39 UTC, angelozerr commented
@datho7561 I cannot reproduce it, could you share a simple example please.

2024-08-14 15:43 UTC, datho7561 commented
> I cannot reproduce it, could you share a simple example please.

https://github.com/user-attachments/assets/9fd454af-f08a-46f7-a180-5b9d3af46e4f

The value of `ASDF_DIR` is `/home/davthomp/.asdf`

2024-08-14 17:21 UTC, angelozerr commented
> Hovering on the system property/environment variable names causes an error popup, and the following is logged in the language server logs:

> Hovering on the system property/environment variable names causes an error popup, and the following is logged in the language server logs:
> 
> Request failed: Request microprofile/propertyDocumentation failed with message: Command 'microprofile/propertyDocumentation' must be called with required MicroProfilePropertyDocumentationParams.sourceType! (-32603).

It should be fixed.

2024-08-14 18:26 UTC, datho7561 requested changes

2024-08-14 18:26 UTC, datho7561 commented on microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/extensions/sysenv/SysEnvItemMetadataProvider.java
> +		return upKey.endsWith("_KEY") || upKey.endsWith("_SECRET") || upKey.endsWith("_PASSOWORD")
`_PASSOWORD` --> `_PASSWORD`

2024-08-15 12:51 UTC, datho7561 commented
Sounds good. I checked out the latest commit and confirmed that's working. Once the tests are in place I think it's ready to go.

2024-08-16 14:45 UTC, merged

2024-08-16 14:45 UTC, angelozerr commented
> Sounds good. I checked out the latest commit and confirmed that's working. Once the tests are in place I think it's ready to go.

Thanks @datho7561 ! I wrote a lot of tests and I merge it since CI build is working well.